-- Borrar el indice con dbeaver


-- CALCULE EL % DE PERSONAS POR REGION, RESPECTO AL TOTAL DEL PAIS
SELECT REGION, COUNT(*) AS NPERSONAS,
COUNT(*)*1.0 / (SELECT COUNT(*) FROM MICRODATO) AS PERC
FROM MICRODATO
GROUP BY REGION
ORDER BY PERC DESC

CREATE INDEX ix_region ON MICRODATO(REGION)

-- COMPARE ESCOLARIDAD PROMEDIO DE PERSONA 1 VS PERSONA 2, POR REGION
SELECT REGION,
AVG(CASE WHEN PERSONAN=1
THEN ESCOLARIDAD ELSE NULL END) AS ESC1,
AVG(CASE WHEN PERSONAN=2
THEN ESCOLARIDAD ELSE NULL END) AS ESC2
FROM MICRODATO
GROUP BY REGION

CREATE INDEX ix_region_personan ON MICRODATO(REGION, PERSONAN)

-- Los indices de sql se parecen a los diccionarios de python, son una estructura de datos
-- que permite acceder a los datos de manera mas rapida