-- CALCULE EL % DE PERSONAS POR REGION, RESPECTO AL TOTAL DEL PAIS
SELECT REGION, COUNT(*) AS NPERSONAS, 
	COUNT(*)*1.0 / (SELECT COUNT(*) FROM MICRODATO) AS PERC
FROM MICRODATO
GROUP BY REGION
ORDER BY PERC DESC

-- CALCULE EL % DE HOGARES POR REGION - version 1
WITH BASE_HOGARES AS (
	SELECT DISTINCT REGION, COMUNA, ID_ZONA_LOC, NVIV, NHOGAR
	FROM MICRODATO
)
SELECT REGION, COUNT(*) AS NHOGARES, 
	COUNT(*)*1.0 / (SELECT COUNT(*) FROM BASE_HOGARES) AS PERC
FROM BASE_HOGARES
GROUP BY REGION
ORDER BY PERC DESC

-- CALCULE EL % DE HOGARES POR REGION - version 2
SELECT REGION, COUNT(*) AS NHOGARES, 
	COUNT(*)*1.0 / (SELECT COUNT(*) FROM MICRODATO WHERE PERSONAN=1) AS PERC
FROM MICRODATO
WHERE PERSONAN=1
GROUP BY REGION
ORDER BY PERC DESC


-- LO MISMO, POR COMUNA
SELECT COMUNA, COUNT(*) AS NPERSONAS, 
	COUNT(*)*1.0 / (SELECT COUNT(*) FROM MICRODATO) AS PERC
FROM MICRODATO
GROUP BY COMUNA
ORDER BY PERC DESC

-- AGREGUE NOMBRE DE COMUNA
SELECT COMUNA, NOMBRE, COUNT(*) AS NPERSONAS, 
	COUNT(*)*1.0 / (SELECT COUNT(*) FROM MICRODATO) AS PERC
FROM MICRODATO LEFT JOIN COMUNAS USING (COMUNA)
GROUP BY COMUNA
ORDER BY PERC DESC


-- CALCULE NUMERO PROMEDIO DE PERSONAS POR HOGAR, POR COMUNA
WITH BASE_HOGARES AS (
SELECT REGION, COMUNA, ID_ZONA_LOC, NVIV, NHOGAR, COUNT(*) AS NPER
FROM MICRODATO
GROUP BY REGION, COMUNA, ID_ZONA_LOC, NVIV, NHOGAR
)
SELECT COMUNA, NOMBRE, AVG(NPER) AS PROMEDIO
FROM BASE_HOGARES LEFT JOIN COMUNAS USING(COMUNA)
GROUP BY COMUNA
ORDER BY PROMEDIO DESC



-- COMPARE ESCOLARIDAD PROMEDIO DE PERSONA 1 VS PERSONA 2, POR REGION

-- VERSION1
SELECT REGION, PERSONAN, AVG(ESCOLARIDAD)
FROM MICRODATO
WHERE PERSONAN = 1 OR PERSONAN = 2
GROUP BY REGION, PERSONAN

--VERSION2 - HACIA EL LADO
SELECT REGION, 
	AVG(CASE WHEN PERSONAN=1 
			THEN ESCOLARIDAD ELSE NULL END) AS ESC1,
	AVG(CASE WHEN PERSONAN=2 
			THEN ESCOLARIDAD ELSE NULL END) AS ESC2
FROM MICRODATO
GROUP BY REGION

-- ENTRE QUE COMUNAS HAY LA MAYOR DIFERENCIA EN NIVEL DE EDUCACION?
SELECT COMUNA, NOMBRE, 
	AVG(CASE WHEN PERSONAN=1 
			THEN ESCOLARIDAD ELSE NULL END) AS ESC1,
	AVG(CASE WHEN PERSONAN=2 
			THEN ESCOLARIDAD ELSE NULL END) AS ESC2,
	ABS(AVG(CASE WHEN PERSONAN=1 
			THEN ESCOLARIDAD ELSE NULL END) - 
		AVG(CASE WHEN PERSONAN=2 
			THEN ESCOLARIDAD ELSE NULL END)) AS DIFF
FROM MICRODATO LEFT JOIN COMUNAS USING(COMUNA)
GROUP BY COMUNA








-- ESCRIBA  UN CÓDIGO QUE  LES MUESTRE LAS MAYORES DIFFERENCIAS DE ESCOLARIDAD ENTRE PERSONA 1 Y PERSONA 2, POR REGION
with base1(
	SELECT COMUNA AS com1, AVG(ESCOLARIDAD) AS esc1
	FROM MICRODATO
	GROUP BY COMUNA
),
base2(
	SELECT COMUNA AS com2, AVG(ESCOLARIDAD) AS esc2
	FROM MICRODATO
	GROUP BY COMUNA
)
SELECT com1, com2, esc1, esc2, ABS(esc1-esc2) AS diff
FROM BASE1 JOIN BASE2